apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-app
  template:
    metadata:
      labels:
        name: redis-app
    spec:
      containers:
      - name: redis-app
        image: loadgeneration.azurecr.io/redis-load-test-image
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo done deploying redis-app; sleep 3600;done"]
        resources:
          requests:
            cpu: 256m
            memory: 500M
          limits:
            cpu: 256m
            memory: 500M
